version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL:-jdbc:postgresql://localhost:5432/improvement_hub}
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=improvement_hub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: