[phases.setup]
cmd = "apt-get update && apt-get install -y maven"

[phases.build]
cmd = "mvn clean package -DskipTests && ls -la target/"

[phases.start]
cmd = "bash -c 'JAR_FILE=$(find target -name \"*.jar\" -type f | head -1); echo \"Starting with JAR: $JAR_FILE\"; java -Dserver.port=$PORT -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar \"$JAR_FILE\"'"

[variables]
JAVA_VERSION = "17"
MAVEN_VERSION = "3.9.6"