[phases.setup]
cmd = "apt-get update && apt-get install -y maven"

[phases.build]
cmd = "mvn clean package -DskipTests"

[phases.start]
cmd = "java -Dserver.port=$PORT -jar target/improvement-hub-backend-1.0.0.jar"

[variables]
JAVA_VERSION = "17"
MAVEN_VERSION = "3.9.6"